image: Visual Studio 2019

environment:
  MSVC_VERSION: "Visual Studio 14"
  INCLUDE: "C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\Include;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\include;C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.10586.0\\ucrt"
  LIB: "C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\lib;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\lib;C:\\Program Files (x86)\\Windows Kits\\10\\lib;C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.10586.0\\ucrt\\x86"

  matrix:
    -  PYTHON: "C:\\Python38-x64"
       SDIST: yes

    -  PYTHON: "C:\\Python36"
       PYTHON_VERSION: 3.6
       PYTHON_ARCH: 32

    -  PYTHON: "C:\\Python37"
       PYTHON_VERSION: 3.7
       PYTHON_ARCH: 32

    -  PYTHON: "C:\\Python38"
       PYTHON_VERSION: 3.8
       PYTHON_ARCH: 32

    -  PYTHON: "C:\\Python39"
       PYTHON_VERSION: 3.9
       PYTHON_ARCH: 32

    -  PYTHON: "C:\\Python36-x64"
       PYTHON_VERSION: 3.6
       PYTHON_ARCH: 64

    -  PYTHON: "C:\\Python37-x64"
       PYTHON_VERSION: 3.7
       PYTHON_ARCH: 64

    -  PYTHON: "C:\\Python38-x64"
       PYTHON_VERSION: 3.8
       PYTHON_ARCH: 64

    -  PYTHON: "C:\\Python39-x64"
       PYTHON_VERSION: 3.9
       PYTHON_ARCH: 64

configuration: Release

init:
  - set PYTHONPATH=%PYTHON%
  - set PYTHONHOME=%PYTHON%
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python -m site
  - python -m pip install -U pip setuptools wheel
  - python -m pip install -U cachetools pefile
  - set PATH=%PATH:C:\Program Files\Meson\;=%

for:
  -
    matrix:
      only:
        - SDIST: yes
    install:
        - python setup.py sdist
    test_script:
        - dir dist

  -
    matrix:
      only:
        - PYTHON_VERSION: 3.6
          PYTHON_ARCH: 32
    install:
        - python setup.py bdist_wheel --python-tag cp36 --plat-name win32

  -
    matrix:
      only:
        - PYTHON_VERSION: 3.7
          PYTHON_ARCH: 32
    install:
        - python setup.py bdist_wheel --python-tag cp37 --plat-name win32

  -
    matrix:
      only:
        - PYTHON_VERSION: 3.8
          PYTHON_ARCH: 32
    install:
        - python setup.py bdist_wheel --python-tag cp38 --plat-name win32

  -
    matrix:
      only:
        - PYTHON_VERSION: 3.9
          PYTHON_ARCH: 32
    install:
        - python setup.py bdist_wheel --python-tag cp39 --plat-name win32

  -
    matrix:
      only:
        - PYTHON_VERSION: 3.6
          PYTHON_ARCH: 64
    install:
        - python setup.py bdist_wheel --python-tag cp36 --plat-name win_amd64

  -
    matrix:
      only:
        - PYTHON_VERSION: 3.7
          PYTHON_ARCH: 64
    install:
        - python setup.py bdist_wheel --python-tag cp37 --plat-name win_amd64

  -
    matrix:
      only:
        - PYTHON_VERSION: 3.8
          PYTHON_ARCH: 64
    install:
        - python setup.py bdist_wheel --python-tag cp38 --plat-name win_amd64

  -
    matrix:
      only:
        - PYTHON_VERSION: 3.9
          PYTHON_ARCH: 64
    install:
        - python setup.py bdist_wheel --python-tag cp39 --plat-name win_amd64


# Not a project with an msbuild file, build done at install.
build: off

before_test:
  - dir dist
  - for /r %%f in (dist/*) do @set wheelname=%%~nxf
  - echo %wheelname%
  - for /F "tokens=2 delims='" %%a in ('findstr __version__ py2exe\__init__.py') do @set ver=%%a
  - echo %ver%

test_script:
  - pip install dist/%wheelname%
  #- pip install --no-index --find-links=dist py2exe
  - python -c "import py2exe"
  - cd tests
  - python maketest.py
  - cd functional
  - runner bundlefiles2_test
  - runner bundlefiles1_test
  - runner bundlefiles0_test
  - runner bundlefiles0_sqlite_test
  - runner bundlefiles0_ssl_test
  - runner numpy_test
  - runner pandas_test
  - runner pycryptodome_test
  - runner tk_test
  #- del "C:\Program Files\Amazon\AWSCLI\sqlite3.dll" /F
  - runner sqlite_test
  - runner certifi_test
  - runner certifi_zip_test
  - runner pywin32_test
  - runner requests_test
  - runner zope_interface_test
  - runner ssl_test

artifacts:
  - path: 'dist/$(wheelname)'
    name: $(wheelname)

# Deploy build to BinTray
deploy:
  provider: BinTray
  username: albertosottile
  api_key:
    secure: XYmBCFZPoLq1hZazcxKJfMx2ueWDBXQg8h3rnOD8z/m/Kv11HuSVTFRDaDtGwKQz
  subject: py2exe
  repo: py2exe
  package: py2exe
  version: $(ver)
  publish: true
  override: true
